export let operation_menu = [{
        name: "首页",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "",
        children: [{
                name: "首页概览",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationHome",
                children: [],
            },
            {
                name: "结算统计",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/settlementStatistics",
                children: [],
            },

        ],
    },
    {
        name: "交易管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/operationTransactionManagement",
        children: [],
    },
    {
        name: "物流管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "",
        children: [{
                name: "查看物流",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationViewLogistics",
                children: [],
            },
            {
                name: "订单派车",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationOrderDispatchCar",
                children: [],
            },
            {
                name: "车辆管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationLogisticsCarsManagement",
                children: [],
            },
            {
                name: "司机管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationLogisticsDriverManagement",
                children: [],
            },
        ],

    },
    {
        name: "物业管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/operationPropertyManage",
        children: [],

    },
    {
        name: "审核管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "",
        children: [{
                name: "入驻审核",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationSettledAudit",
                children: [],
            },
            {
                name: "商品审核",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationProductAudit",
                children: [],
            },
            {
                name: "美食审核",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationDeliciousFood",
                children: [],
            }
        ],

    },
    {
        name: "报表管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "",
        children: [{
                name: "交易报表",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationTradeReport",
                children: [],
            },
            {
                name: "商户交易报表",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationMerchantTradeReport",
                children: [],
            },
            {
                name: "物业报表",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationPropertyReport",
                children: [],
            },
        ],
    },
    {
        name: "信息管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "",
        children: [{
                name: "信息发布",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationInfoRelease",
                children: [],
            },
            {
                name: "仓库管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/warehouseManagement",
                children: [],
            },
            {
                name: "系统参数",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/Systemreference",
                children: [],
            },
            {
                name: "药品分类",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/drugClassification",
                children: [],
            },
            {
                name: "药品管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/drugManagement",
                children: [],
            },
            {
                name: "药械分类",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/mechanicalClassification",
                children: [],
            },

            {
                name: "药械管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/medicineManagement",
                children: [],
            },
            {
                name: "数据字典",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/dataDictionary",
                children: [],
            },
            {
                name: "商城分类",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/Classification",
                children: [],
            },
            {
                name: "关于我们",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationAboutus",
                children: [],
            }
        ],
    },
    {
        name: "账号管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "",
        children: [{
                name: "账号安全",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationAccountSecurity",
                children: [],
            },
            {
                name: "权限账号管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationAccountManage",
                children: [],
            },
            {
                name: "角色管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationRoleManagement",
                children: [],
            },
            {
                name: "登录日志",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationLoginLog",
                children: [],
            },
            {
                name: "接入管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationAccessManage",
                children: [],
            },
        ],
    },
    {
        name: "用户管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "",
        children: [{
                name: "供应商管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationSupplierManage",
                children: [],
            },
            {
                name: "采购商管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationPurchaserManage",
                children: [],
            },
            {
                name: "监管机构管理",
                iconSvg: require("@/assets/images/aside/GZT.svg"),
                iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
                state: 2,
                path: "/operationRegulatoryAuthorityManagement",
                children: [],
            },
        ],
    },

]