export let purchaser_menu = [{
  name: "首页",
  iconSvg: require("../assets/images/aside/GZT.svg"),
  iconSvgAction: require("../assets/images/aside/GZT-Action.svg"),
  state: 2,
  path: "/purchaserHome",
  children: [],
},
{
  name: "交易管理",
  iconSvg: require("../assets/images/aside/GZT.svg"),
  iconSvgAction: require("../assets/images/aside/GZT-Action.svg"),
  state: 2,
  path: "",
  children: [{
    name: "交易订单明细",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/transactionOrderDetails",
    children: [],
  },
  {
    name: "退货订单明细",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/returnOrderDetails",
    children: [],
  },

  ],
},
{
  name: "采购管理",
  iconSvg: require("../assets/images/aside/GZT.svg"),
  iconSvgAction: require("../assets/images/aside/GZT-Action.svg"),
  state: 2,
  path: "",
  children: [{
    name: "采购登记",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/procurementRegistration",
    children: [],
  },
  {
    name: "我的购物车",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/myShoppingCart",
    children: [],
  },
  {
    name: "我的采购单",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/myPurchaseOrder",
    children: [],
  },
  {
    name: "采购单审核",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/purchaseOrderApproval",
    children: [],
  },
  {
    name: "审核记录",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/auditRecord",
    children: [],
  },
  ],
},
{
  name: "供应商管理",
  iconSvg: require("../assets/images/aside/GZT.svg"),
  iconSvgAction: require("../assets/images/aside/GZT-Action.svg"),
  state: 2,
  path: "/supplierManagement",
  children: [],
},
{
  name: "账号管理",
  iconSvg: require("../assets/images/aside/GZT.svg"),
  iconSvgAction: require("../assets/images/aside/GZT-Action.svg"),
  state: 2,
  path: "",
  children: [{
    name: "企业信息管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/enterpriseInformationManagement",
    children: [],
  },
  {
    name: "账号安全",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/accountSecurity",
    children: [],
  },
  {
    name: "收货地址管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/receivingAddressManagement",
    children: [],
  },
  {
    name: "权限账号管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/authorityAccountManagement",
    children: [],
  },
  {
    name: "角色管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/roleManagement",
    children: [],
  },
  {
    name: "登录日志",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/loginLog",
    children: [],
  },
  ],
},
{
  name: "发票管理",
  iconSvg: require("../assets/images/aside/GZT.svg"),
  iconSvgAction: require("../assets/images/aside/GZT-Action.svg"),
  state: 2,
  path: "/controlOverInvoices",
  children: [],
},
{
  name: "结算中心",
  iconSvg: require("../assets/images/aside/GZT.svg"),
  iconSvgAction: require("../assets/images/aside/GZT-Action.svg"),
  state: 2,
  path: "",
  children: [{
    name: "支付结算中心",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/paymentSettlementCenter",
    children: [],
  }, {
    name: "银行卡管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/bankCardManagement",
    children: [],
  },
  {
    name: "信用付",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/creditPayment",
    children: [],
  },
  ],
},
]
