export let supplier_menu = [{
    name: "首页概览",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/supplierHome",
    children: [],
  },
  {
    name: "交易管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "",
    children: [
      {
        name: "集采订单明细",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierTransactionOrderList",
        children: [],
      },
      {
        name: "零售订单明细",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierRetailOrderList",
        children: [],
      },
      {
        name: "销售日报统计",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierSalesDailyStatistics",
        children: [],
      },
      {
        name: "商品销售统计",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierCommoditySalesStatistics",
        children: [],
      },
    ],
  },
  {
    name: "物流管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "",
    children: [
      {
        name: "物流跟踪",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierLogisticsTracking",
        children: [],
      },
      {
        name: "运费模板",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierLogisticsShippingTemplate",
        children: [],
      },
    ],
  },
  {
    name: "商品管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "",
    children: [
      {
        name: "药品管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierProductManage",
        children: [],
      },
      {
        name: "药械管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierInstrumentManage",
        children: [],
      },
    ],
  },
  {
    name: "采购商管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "/supplierPurchaserManage",
    children: [],
  },
  {
    name: "账号管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "",
    children: [
      {
        name: "企业信息管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierEnterpriseInfoManage",
        children: [],
      },
      {
        name: "账号安全",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierAccountSecurity",
        children: [],
      },
      {
        name: "权限账号管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierAccountManagement",
        children: [],
      },
      {
        name: "角色管理",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierRoleManagement",
        children: [],
      },
      {
        name: "登录日志",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierLoginLog",
        children: [],
      },
    ],
  },
  {
    name: "发票管理",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "",
    children: [
      {
        name: "已开发票",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierInvoiced",
        children: [],
      },
      {
        name: "发票上传",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierInvoiceUpload",
        children: [],
      },
    ],
  },
  {
    name: "结算中心",
    iconSvg: require("@/assets/images/aside/GZT.svg"),
    iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
    state: 2,
    path: "",
    children: [
      {
        name: "结算首页",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierSettlementHome",
        children: [],
      },
      {
        name: "结算统计",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierSettlementStatistics",
        children: [],
      },
      {
        name: "信用贷",
        iconSvg: require("@/assets/images/aside/GZT.svg"),
        iconSvgAction: require("@/assets/images/aside/GZT-Action.svg"),
        state: 2,
        path: "/supplierCreditLoan",
        children: [],
      },
    ],
  },

]
